# Generated by Django 5.1.6 on 2025-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Personal Data',
                'ordering': ['name'],
            },
        ),
    ]
