# Generated by Django 5.1.6 on 2025-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_column='Age')),
                ('restingbp', models.IntegerField(db_column='RestingBP')),
                ('cholesterol', models.IntegerField(db_column='Cholesterol')),
                ('fastingbs', models.IntegerField(db_column='FastingBS')),
                ('maxhr', models.IntegerField(db_column='MaxHR')),
                ('oldpeak', models.FloatField(db_column='Oldpeak')),
                ('heartdisease', models.IntegerField(db_column='HeartDisease')),
                ('patientid', models.IntegerField(db_column='PatientID')),
                ('timestep', models.IntegerField(db_column='TimeStep')),
                ('heartrate', models.FloatField(db_column='HeartRate')),
                ('oxygensaturation', models.FloatField(db_column='OxygenSaturation')),
                ('sex_m', models.FloatField(db_column='Sex_M')),
                ('chestpaintype_ata', models.FloatField(db_column='ChestPainType_ATA')),
                ('chestpaintype_nap', models.FloatField(db_column='ChestPainType_NAP')),
                ('chestpaintype_ta', models.FloatField(db_column='ChestPainType_TA')),
                ('restingecg_normal', models.FloatField(db_column='RestingECG_Normal')),
                ('restingecg_st', models.FloatField(db_column='RestingECG_ST')),
                ('exerciseangina_1', models.FloatField(db_column='ExerciseAngina_1')),
                ('st_slop_flat', models.FloatField(db_column='ST_Slop_Flat')),
                ('st_slop_up', models.FloatField(db_column='ST_Slop_Up')),
                ('deviceid', models.IntegerField(db_column='deviceID', unique=True)),
            ],
            options={
                'db_table': 'ftable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_column='Age')),
                ('sex', models.TextField(db_column='Sex')),
                ('chestpaintype', models.TextField(db_column='ChestPainType')),
                ('restingbp', models.IntegerField(db_column='RestingBP')),
                ('cholestrol', models.IntegerField(db_column='Cholestrol')),
                ('fastingbs', models.IntegerField(db_column='FastingBS')),
                ('restingecg', models.TextField(db_column='RestingECG')),
                ('maxhr', models.IntegerField(db_column='MaxHR')),
                ('exerciseangina', models.IntegerField(db_column='ExerciseAngina')),
                ('oldpeak', models.FloatField(db_column='Oldpeak')),
                ('st_slope', models.TextField(db_column='ST_Slope')),
                ('heartdisease', models.IntegerField(db_column='HeartDisease')),
                ('patientid', models.IntegerField(db_column='PatientID')),
                ('timestep', models.IntegerField(db_column='TimeStep')),
                ('heartrate', models.FloatField(db_column='HeartRate')),
                ('bloodpressure', models.FloatField(db_column='BloodPressure')),
                ('oxygensaturation', models.FloatField(db_column='OxygenSaturation')),
                ('deviceid', models.IntegerField(db_column='deviceID', unique=True)),
            ],
            options={
                'db_table': 'stable',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='patientdata',
        ),
    ]
