# Generated by Django 5.1.6 on 2025-03-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=1)),
                ('ChestPain', models.CharField(max_length=3)),
                ('RestingBD', models.IntegerField()),
                ('Cholesterol', models.IntegerField()),
                ('FastingBS', models.IntegerField()),
                ('RestingECG', models.CharField(max_length=3)),
                ('MaxHR', models.IntegerField()),
                ('ExerciseAngina', models.CharField(max_length=1)),
                ('Oldpeak', models.FloatField()),
                ('ST_Slope', models.CharField(max_length=4)),
            ],
        ),
    ]
