# Generated by Django 5.1.6 on 2025-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show_reports', '0002_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=1)),
                ('ChestPainType', models.CharField(max_length=3)),
                ('RestingBP', models.IntegerField()),
                ('Cholesterol', models.IntegerField()),
                ('FastingBS', models.IntegerField()),
                ('RestingECG', models.CharField(max_length=3)),
                ('MaxHR', models.IntegerField()),
                ('ExerciseAngina', models.CharField(max_length=1)),
                ('Oldpeak', models.FloatField()),
                ('ST_Slope', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['Age'],
            },
        ),
    ]
