# Generated by Django 5.2.2 on 2025-06-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_reports', '0005_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_column='Age')),
                ('restingbp', models.IntegerField(db_column='RestingBP')),
                ('cholesterol', models.IntegerField(db_column='Cholesterol')),
                ('fastingbs', models.IntegerField(db_column='FastingBS')),
                ('maxhr', models.IntegerField(db_column='MaxHR')),
                ('oldpeak', models.FloatField(db_column='Oldpeak')),
                ('heartdisease', models.IntegerField(db_column='HeartDisease')),
                ('patientid', models.IntegerField(db_column='PatientID')),
                ('timestep', models.IntegerField(db_column='TimeStep')),
                ('heartrate', models.FloatField(db_column='HeartRate')),
                ('oxygensaturation', models.FloatField(db_column='OxygenSaturation')),
                ('sex_m', models.FloatField(db_column='Sex_M')),
                ('chestpaintype_ata', models.FloatField(db_column='ChestPainType_ATA')),
                ('chestpaintype_nap', models.FloatField(db_column='ChestPainType_NAP')),
                ('chestpaintype_ta', models.FloatField(db_column='ChestPainType_TA')),
                ('restingecg_normal', models.FloatField(db_column='RestingECG_Normal')),
                ('restingecg_st', models.FloatField(db_column='RestingECG_ST')),
                ('exerciseangina_1', models.FloatField(db_column='ExerciseAngina_1')),
                ('st_slop_flat', models.FloatField(db_column='ST_Slop_Flat')),
                ('st_slop_up', models.FloatField(db_column='ST_Slop_Up')),
                ('deviceid', models.IntegerField(db_column='deviceID', unique=True)),
            ],
            options={
                'db_table': 'ftable',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'managed': False},
        ),
    ]
